# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=45)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_quote.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quotes', models.ManyToManyField(through='daily_quote.Ranked', to='daily_quote.Quote')),
            ],
        ),
        migrations.AddField(
            model_name='ranked',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_quote.User'),
        ),
    ]
