# Generated by Django 2.0 on 2018-01-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quote_me', '0001_initial'),
        ('daily_quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterank',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quote_me.Profile'),
        ),
        migrations.AddField(
            model_name='quoterank',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daily_quote.Quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daily_quote.Author'),
        ),
    ]
