# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranked',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
