# Generated by Django 2.0 on 2018-01-05 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quote', '0002_auto_20180102_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterank',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
