# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_quote', '0003_quoterank_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('current_quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_quote', to='daily_quote.Quote')),
            ],
        ),
        migrations.AlterField(
            model_name='quoterank',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daily_quote.Profile'),
        ),
        migrations.AlterField(
            model_name='quoterank',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quotes',
            field=models.ManyToManyField(through='daily_quote.QuoteRank', to='daily_quote.Quote'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
