# Generated by Django 2.0 on 2018-01-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_quote_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
