# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quote', '0004_auto_20180109_2300'),
        ('quote_me', '0002_profile_current_quote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
