stock_users = [{
        'username': 'alice',
        'first_name': 'Alice',
        'last_name': 'Doe',
    }, {
        'username': 'bob',
        'first_name': 'Bob',
        'last_name': 'Doe',
    }, {
        'username': 'eve',
        'first_name': 'Eve',
        'last_name': 'Doe',
    }, {
        'username': 'john',
        'first_name': 'John',
        'last_name': 'Lennon',
    }, {
        'username': 'paul',
        'first_name': 'Paul',
        'last_name': 'McCartney',
    }, {
        'username': 'george',
        'first_name': 'George',
        'last_name': 'Harrison',
    }, {
        'username': 'ringo',
        'first_name': 'Ringo',
        'last_name': 'Starr',
    }, {
        'username': 'pete',
        'first_name': 'Pete',
        'last_name': 'Best',
    }, {
        'username': 'rathgar',
        'first_name': 'Rathgar',
        'last_name': 'Ireland',
    }, {
        'username': 'steve',
        'first_name': 'Steve',
        'last_name': 'Doe',
    }, {
        'username': 'robert',
        'first_name': 'Robert',
        'last_name': 'Doe',
    }]